// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3BSinYy-nokYnwhsRC9ZU65f8FJG-oAk',
    appId: '1:246446001659:web:6beccba559b692b5460f5e',
    messagingSenderId: '246446001659',
    projectId: 'maxfit-dev-2023',
    authDomain: 'maxfit-dev-2023.firebaseapp.com',
    storageBucket: 'maxfit-dev-2023.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgE_CgCwWvjzovGirEo2x5o0jypYu1xOo',
    appId: '1:246446001659:ios:07d9509673fc8eb5460f5e',
    messagingSenderId: '246446001659',
    projectId: 'maxfit-dev-2023',
    storageBucket: 'maxfit-dev-2023.appspot.com',
    androidClientId: '246446001659-5u4p1q66caabpb4itp13r66vicdvqjm2.apps.googleusercontent.com',
    iosClientId: '246446001659-25pgaar0gniipjkbbturslaviaed9pbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxfit.RunnerTests',
  );
}
